<a href="https://colab.research.google.com/github/sumathiselvan79/CE7454_2019/blob/master/day3session2numpyex2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Write a Pandas program to create and display a one-dimensional array using series  containing  even numbers upto 10

In [ ]:
import pandas as pd
ds = pd.Series([2, 4, 6, 8,10]) 
print(ds)




0     2
1     4
2     6
3     8
4    10
dtype: int64


# Write a Pandas program to convert a Panda module Series to Python list and its type.

In [ ]:
import pandas as pd
ds = pd.Series([2, 4, 6, 8, 10])
print("Pandas Series and type")
print(ds)
print(type(ds))
print("Convert Pandas Series to Python list")
print(ds.tolist())
print(type(ds.tolist()))


Pandas Series and type
0     2
1     4
2     6
3     8
4    10
dtype: int64
<class 'pandas.core.series.Series'>
Convert Pandas Series to Python list
[2, 4, 6, 8, 10]
<class 'list'>


# Write a Pandas program to add, subtract, multiple and divide two Pandas Series. Sample Series: [2, 4, 6, 8, 10], [1, 3, 5, 7, 9]


In [ ]:
import pandas as pd
ds1 = pd.Series([2, 4, 6, 8, 10])
ds2 = pd.Series([1, 3, 5, 7, 9])
ds = ds1 + ds2
print("Add two Series:")
print(ds)
print("Subtract two Series:")
ds = ds1 - ds2
print(ds)
print("Multiply two Series:")
ds = ds1 * ds2
print(ds)
print("Divide Series1 by Series2:")
ds = ds1 / ds2
print(ds)


Add two Series:
0     3
1     7
2    11
3    15
4    19
dtype: int64
Subtract two Series:
0    1
1    1
2    1
3    1
4    1
dtype: int64
Multiply two Series:
0     2
1    12
2    30
3    56
4    90
dtype: int64
Divide Series1 by Series2:
0    2.000000
1    1.333333
2    1.200000
3    1.142857
4    1.111111
dtype: float64


#Write a Pandas program to compare the elements of the two Pandas Series.
#Sample Series: [2, 4, 6, 8, 10], [1, 3, 5, 7, 9]



In [ ]:
import pandas as pd
ds1 = pd.Series([2, 4, 6, 8, 10])
ds2 = pd.Series([1, 3, 5, 7, 10])
print("Series1:")
print(ds1)
print("Series2:")
print(ds2)
print("Compare the elements of the said Series:")
print("Equals:")
print(ds1 == ds2)
print("Greater than:")
print(ds1 > ds2)
print("Less than:")
print(ds1 < ds2)


Series1:
0     2
1     4
2     6
3     8
4    10
dtype: int64
Series2:
0     1
1     3
2     5
3     7
4    10
dtype: int64
Compare the elements of the said Series:
Equals:
0    False
1    False
2    False
3    False
4     True
dtype: bool
Greater than:
0     True
1     True
2     True
3     True
4    False
dtype: bool
Less than:
0    False
1    False
2    False
3    False
4    False
dtype: bool


#Write a Pandas program to convert a dictionary to a Pandas series.
#Sample dictionary: d1 = {'a': 100, 'b': 200, 'c':300, 'd':400, 'e':800}


In [ ]:
import pandas as pd
d1 = {'a': 100, 'b': 200, 'c':300, 'd':400, 'e':800}
print("Original dictionary:")
print(d1)
new_series = pd.Series(d1)
print("Converted series:")
print(new_series)


Original dictionary:
{'a': 100, 'b': 200, 'c': 300, 'd': 400, 'e': 800}
Converted series:
a    100
b    200
c    300
d    400
e    800
dtype: int64


#Write a Pandas program to convert a NumPy array to a Pandas series.
#Sample NumPy array: d1 = [10, 20, 30, 40, 50]


In [ ]:
import numpy as np
import pandas as pd
np_array = np.array([10, 20, 30, 40, 50])
print("NumPy array:")
print(np_array)
new_series = pd.Series(np_array)
print("Converted Pandas series:")
print(new_series)


NumPy array:
[10 20 30 40 50]
Converted Pandas series:
0    10
1    20
2    30
3    40
4    50
dtype: int64


#Write a Pandas program to change the data type of the given  Series into numeric
#['100', '200', 'python', '300.12', '400']


In [ ]:
import pandas as pd
s1 = pd.Series(['100', '200', 'python', '300.12', '400a'])
print("Original Data Series:")
print(s1)
print("Change the said data type to numeric:")
s2 = pd.to_numeric(s1, errors='coerce')
print(s2)


Original Data Series:
0       100
1       200
2    python
3    300.12
4      400a
dtype: object
Change the said data type to numeric:
0    100.00
1    200.00
2       NaN
3    300.12
4       NaN
dtype: float64


# Write a Pandas program to convert a given Series to an array.

In [ ]:
import numpy as np
s1 = pd.Series(['100', '200', 'python', '300.12', '400'])
print("Original Data Series:")
print(s1)
print("Series to an array")
a = np.array(s1.values.tolist())
print (a)


Original Data Series:
0       100
1       200
2    python
3    300.12
4       400
dtype: object
Series to an array
['100' '200' 'python' '300.12' '400']


#Write a Pandas program to sort a given Series.

In [ ]:
import pandas as pd
s = pd.Series(['200','100','python', '300.12', '400'])
print("Original Data Series:")
print(s)
new_s = pd.Series(s).sort_values()
print(new_s)


Original Data Series:
0       200
1       100
2    python
3    300.12
4       400
dtype: object
1       100
0       200
3    300.12
4       400
2    python
dtype: object


#Write a Pandas program to add some data to an existing Series.

In [ ]:
import pandas as pd
s = pd.Series(['100', '200', 'python', '300.12', '400'])
print("Original Data Series:")
print(s)
print("\nData Series after adding some data:")
new_s = s.append(pd.Series(['500', 'php']))
print(new_s)


Original Data Series:
0       100
1       200
2    python
3    300.12
4       400
dtype: object

Data Series after adding some data:
0       100
1       200
2    python
3    300.12
4       400
0       500
1       php
dtype: object


#Write a Pandas program to create a subset of a given series based on value and condition.

In [ ]:
import pandas as pd
s = pd.Series([0, 1,2,3,4,5,6,7,8,9,10])
print("Original Data Series:")
print(s)
print("\nSubset of the above Data Series:")
n = 6
new_s = s[s >n]
print(new_s)


Original Data Series:
0      0
1      1
2      2
3      3
4      4
5      5
6      6
7      7
8      8
9      9
10    10
dtype: int64

Subset of the above Data Series:
7      7
8      8
9      9
10    10
dtype: int64


#Write a Pandas program to change the order of index of a given series.

In [ ]:
import pandas as pd
s = pd.Series(data = [1,2,3,4,5], index = ['A', 'B', 'C','D','E'])
print("Original Data Series:")
print(s)
s = s.reindex(index = ['B','A','C','D','E'])
print("Data Series after changing the order of index:")
print(s)


Original Data Series:
A    1
B    2
C    3
D    4
E    5
dtype: int64
Data Series after changing the order of index:
B    2
A    1
C    3
D    4
E    5
dtype: int64


#Write a Pandas program to create the mean and standard deviation, maximum and minimum of the data of a given Series.

In [ ]:
import pandas as pd
s = pd.Series(data = [1,2,3,4,5,6,7,8,9,5,3])
print("Original Data Series:")
print(s)
print("Mean of the said Data Series:")
print(s.mean())
print("Standard deviation of the said Data Series:")
print(s.std())


Original Data Series:
0     1
1     2
2     3
3     4
4     5
5     6
6     7
7     8
8     9
9     5
10    3
dtype: int64
Mean of the said Data Series:
4.818181818181818
Standard deviation of the said Data Series:
2.522624895547565


#Write a Pandas program to get the elements of an array values into column-wise.
#Sample data: {‘X’:[78,85,96,80,86], 'Y':[84,94,89,83,86],'Z':[86,97,96,72,83]}


In [ ]:
import pandas as pd
df = pd.DataFrame({'X':[78,85,96,80,86], 'Y':[84,94,89,83,86],'Z':[86,97,96,72,83]});
print(df)


    X   Y   Z
0  78  84  86
1  85  94  97
2  96  89  96
3  80  83  72
4  86  86  83


#Write a Pandas program to get the columns of the DataFrame (movies_metadata.csv file).

In [ ]:
import pandas as pd
import numpy as np
df = pd.read_csv('/content/movie_metadata.csv')
print("Columns of the DataFrame:")
print(df.columns)


Columns of the DataFrame:
Index(['color', 'director_name', 'num_critic_for_reviews', 'duration',
       'director_facebook_likes', 'actor_3_facebook_likes', 'actor_2_name',
       'actor_1_facebook_likes', 'gross', 'genres', 'actor_1_name',
       'movie_title', 'num_voted_users', 'cast_total_facebook_likes',
       'actor_3_name', 'facenumber_in_poster', 'plot_keywords',
       'movie_imdb_link', 'num_user_for_reviews', 'language', 'country',
       'content_rating', 'budget', 'title_year', 'actor_2_facebook_likes',
       'imdb_score', 'aspect_ratio', 'movie_facebook_likes', 'Unnamed: 28'],
      dtype='object')


#Write a Pandas program to sort the DataFrame based on country from dataset of 
# movie_metadata.csv


In [ ]:
import pandas as pd
import numpy as np
df = pd.read_csv('/content/movie_metadata.csv')
print("sorted by country")
small_df = df[['num_user_for_reviews','language','country','content_rating','budget','title_year']]
result = small_df.sort_values('country')
print("DataFrame based on release date.")
print(result)


sorted by country
DataFrame based on release date.
     num_user_for_reviews language  ...     budget title_year
4735                   77     Dari  ...    46000.0     2003.0
4450                   37  Spanish  ...  1400000.0     2004.0
4666                   11  Spanish  ...   800000.0     2004.0
4415                  125  Spanish  ...  1500000.0     2000.0
4000                  231  Spanish  ...  2000000.0     2009.0
...                   ...      ...  ...        ...        ...
4                     NaN      NaN  ...        NaN        NaN
279                   NaN      NaN  ...        NaN        NaN
2370                  NaN  English  ...        NaN        NaN
3397                   85  English  ...        NaN        NaN
4021                   13  English  ...  3500000.0     2014.0

[5043 rows x 6 columns]


#Write a Pandas program to get the details of the thrid movie of the DataFrame #(movie_metadata.csv file).

In [ ]:
import pandas as pd
df = pd.read_csv('/content/movie_metadata.csv')
third_movie = df.iloc[2]
print("Details of the third moviee:")
print(third_movie)


Details of the third moviee:
color                                                                    Color
director_name                                                       Sam Mendes
num_critic_for_reviews                                                     602
duration                                                                   148
director_facebook_likes                                                      0
actor_3_facebook_likes                                                     161
actor_2_name                                                      Rory Kinnear
actor_1_facebook_likes                                                   11000
gross                                                              2.00074e+08
genres                                               Action|Adventure|Thriller
actor_1_name                                                   Christoph Waltz
movie_title                                                           Spectre 
num_voted_users        

#Write a Pandas program to display the first 10 rows of the DataFrame.

In [ ]:
import pandas as pd
df = pd.read_csv('/content/movie_metadata.csv')
#Display the first 10 rows
result = df.head(10)
print("First 10 rows of the DataFrame:")
print(result)



First 10 rows of the DataFrame:
   color      director_name  ...  movie_facebook_likes  Unnamed: 28
0  Color      James Cameron  ...                 33000          NaN
1  Color     Gore Verbinski  ...                     0          NaN
2  Color         Sam Mendes  ...                 85000          NaN
3  Color  Christopher Nolan  ...                164000          NaN
4    NaN        Doug Walker  ...                     0          NaN
5  Color     Andrew Stanton  ...                 24000          NaN
6  Color          Sam Raimi  ...                     0          NaN
7  Color       Nathan Greno  ...                 29000          NaN
8  Color        Joss Whedon  ...                118000          NaN
9  Color        David Yates  ...                 10000          NaN

[10 rows x 29 columns]


#Write a NumPy program to generate five random numbers from the normal distribution.

In [ ]:
import numpy as np
x = np.random.normal(size=5)
print(x)


[ 0.4504374   1.48574298 -0.44130498  0.47918074  0.95390692]


#Write a NumPy program to generate six random integers between 10 and 30

In [ ]:
import numpy as np
x = np.random.randint(low=10, high=30, size=6)
print(x)


[13 24 10 22 14 19]


#Write a NumPy program to create a 3x3x3 array with random values.

In [ ]:
import numpy as np
x = np.random.random((3,3,3))
print(x)


[[[0.43204717 0.34553488 0.06671254]
  [0.49987601 0.96921187 0.8717562 ]
  [0.05696434 0.629598   0.29506387]]

 [[0.74547158 0.03887758 0.91019283]
  [0.85181954 0.17346535 0.04123725]
  [0.32283476 0.90070007 0.54147532]]

 [[0.27293677 0.31775246 0.45753039]
  [0.11139665 0.56380353 0.17812434]
  [0.87385451 0.73578157 0.42265836]]]


#Write a NumPy program to create a 5x5 array with random values and find the minimum #and maximum values.

In [ ]:
import numpy as np
x = np.random.random((5,5))
print("Original Array:")
print(x) 
xmin, xmax = x.min(), x.max()
print("Minimum and Maximum Values:")
print(xmin, xmax)


Original Array:
[[0.27486466 0.35012904 0.67178631 0.58362038 0.89323997]
 [0.27376607 0.46432733 0.22006923 0.19787976 0.86954942]
 [0.66321764 0.40018856 0.33148432 0.35229014 0.21533472]
 [0.98875063 0.02877008 0.64246896 0.70377159 0.77405163]
 [0.88019974 0.22789282 0.26274037 0.130056   0.40921491]]
Minimum and Maximum Values:
0.028770079429119244 0.9887506309646977


#Write a NumPy program to create a random 10x4 array and extract the first five  rows of the array and store them into a variable.


In [ ]:
import numpy as np
x = np.random.rand(10, 4)
print("Original array: ")
print(x)
y= x[:5, :]
print("First 5 rows of the above array:")
y= x[:5, :]
print(y)
z= x[:, :4]
print("First 3 columns of the above array:")
print(z)



Original array: 
[[0.20677407 0.93185139 0.10208176 0.95900903]
 [0.68371115 0.04684594 0.57536526 0.62925824]
 [0.56710511 0.33870742 0.01202919 0.81304071]
 [0.45284751 0.82259197 0.94462496 0.60232102]
 [0.17422311 0.74790313 0.27824946 0.27676311]
 [0.59608785 0.57448    0.57765533 0.58369031]
 [0.93881605 0.63022803 0.57586975 0.37982829]
 [0.76278571 0.4193296  0.6821853  0.57616404]
 [0.9000036  0.62565447 0.60656909 0.28183149]
 [0.27895007 0.15691315 0.75753022 0.15737406]]
First 5 rows of the above array:
[[0.20677407 0.93185139 0.10208176 0.95900903]
 [0.68371115 0.04684594 0.57536526 0.62925824]
 [0.56710511 0.33870742 0.01202919 0.81304071]
 [0.45284751 0.82259197 0.94462496 0.60232102]
 [0.17422311 0.74790313 0.27824946 0.27676311]]
First 3 columns of the above array:
[[0.20677407 0.93185139 0.10208176 0.95900903]
 [0.68371115 0.04684594 0.57536526 0.62925824]
 [0.56710511 0.33870742 0.01202919 0.81304071]
 [0.45284751 0.82259197 0.94462496 0.60232102]
 [0.17422311 0.7479

#Write a NumPy program to shuffle numbers and find permutation  between 0 and 10 #(inclusive).



In [ ]:
import numpy as np
x = np.arange(10)
np.random.shuffle(x)
print(x)
print("Same result using permutation():")
print(np.random.permutation(10))


[7 4 8 9 2 5 0 6 1 3]
Same result using permutation():
[2 6 5 9 1 3 8 0 4 7]


#Write a NumPy program to create a random integer nos of size 10 and sort it.

In [ ]:
import numpy as np
x=np.arange(10)
np.random.randint(0,10)
print (x)


[0 1 2 3 4 5 6 7 8 9]


#Write a NumPy program to create a random integer nos of size 10 and sort it.

In [ ]:
import numpy as np
x=np.arange(10)
np.random.shuffle(x)
print(x)
x.sort()
print(x)


[1 0 6 4 2 9 7 5 8 3]
[0 1 2 3 4 5 6 7 8 9]
